layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Kubernetes
    web_url: https://kubernetes.io
    image_url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo_with_border.png

  - name: Google Cloud Platform
    web_url: https://cloud.google.com/
    image_url: https://cdn-images-1.medium.com/max/2400/1*CMz4r3-pEFp3Po6oHv-JxQ.png
  
  - name: Go
    web_url: https://golang.org/
    image_url: https://cdn-images-1.medium.com/max/1600/1*i2skbfmDsHayHhqPfwt6pA.png
  